query Posts($after: String = "", $limit: Int = 10) {
  posts(after: $after, first: $limit) {
    nodes {
      id
      title
      excerpt
      date
      uri
      featuredImage {
        node {
          sourceUrl
          srcSet
        }
      }
      categories {
        nodes {
          id
          name
          slug
        }
      }
      commentCount
    }
    pageInfo {
      endCursor
      hasNextPage
    }
  }
}